version: "1"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_name: postgres
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    networks:
      - skynet
      
  spring:
    container_name: backend
    image: backend:v1
    build: ./backend/
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres?serverTimezone=UTC&useLegacyDatetimeCode=false

    ports:
      - 8080:8080
    networks:
      - skynet

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx_data/build:/usr/share/nginx/html
      - ./nginx_data/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - skynet

volumes:
  postgres_data:
  nginx_data:



networks:
  skynet:
    driver: bridge  

